1. Install your load balancer

diff --git a/0x0F-load_balancer/1-install_load_balancer b/0x0F-load_balancer/1-install_load_balancer
--- a/0x0F-load_balancer/1-install_load_balancer
+++ b/0x0F-load_balancer/1-install_load_balancer
@@ -1,34 +1,46 @@
 #!/usr/bin/env bash
-# Install HAProxy
+# Exit on errors
+set -e
 
-sudo apt update
-sudo apt install -y haproxy
+# Update package list and install HAProxy
+sudo apt-get update -y
+sudo apt-get install -y haproxy
 
-# Configure HAPproxy
-sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak
+# Configure HAProxy
+sudo mv /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.bak  # Backup the default configuration file
 
+# Create a new HAProxy configuration file
 sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOL
-frontend http_front
-    bind *:8080
+global
+    log /dev/log local0
+    log /dev/log local1 notice
+    user haproxy
+    group haproxy
+    daemon
+
+defaults
+    log global
     mode http
+    option httplog
+    option dontlognull
+    retries 3
+    option redispatch
+    timeout connect 5s
+    timeout client 15s
+    timeout server 15s
+
+frontend http_front
+    bind *:80
     stats uri /haproxy?stats
-    timeout client 30s
-    timeout connect 30s
-    timeout server 30s
     default_backend http_back
 
 backend http_back
     balance roundrobin
-    server web-01 54.88.251.127:8080 check
-    server web-02 54.86.197.249:8080 check
-    timeout client 30s
-    timeout server 30s
+    server web-01 100.26.9.108:80 check
+    server web-02 34.207.57.168:80 check
 EOL
 
-# Ensure HAProxy can be managed via init script
-sudo service haproxy restart
+# Restart HAProxy to apply changes
+sudo systemctl restart haproxy
 
-sudo haproxy -c -f /etc/haproxy/haproxy.cfg
-
-# Display a messagew indicating succesful configuration
-echo "HAProxy has been installed and configured successfully!"
+echo "HAProxy configuration completed successfully."
